// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type RefreshToken struct {
	UserID    string
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsRevoked int64
	ExpiresAt time.Time
}

type Task struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DueUntil    time.Time
	Title       string
	Description string
	Priority    int64
	Category    string
	UserID      string
}

type User struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	Username       string
	HashedPassword string
	IsAdmin        int64
}
