// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type RefreshToken struct {
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsRevoked int64
	ExpiresAt time.Time
}

type User struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	Username       string
	HashedPassword string
}
