// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package database

import (
	"context"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks(id, created_at, updated_at, due_until, title, description, priority, category, user_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, due_until, title, description, priority, category, user_id
`

type CreateTaskParams struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DueUntil    time.Time
	Title       string
	Description string
	Priority    int64
	Category    string
	UserID      string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DueUntil,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Category,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueUntil,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Category,
		&i.UserID,
	)
	return i, err
}

const deleteTaskByID = `-- name: DeleteTaskByID :exec
DELETE FROM tasks WHERE id = ? AND user_id = ?
`

type DeleteTaskByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteTaskByID(ctx context.Context, arg DeleteTaskByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteTaskByID, arg.ID, arg.UserID)
	return err
}

const getAllUsersTasks = `-- name: GetAllUsersTasks :many
SELECT id, created_at, updated_at, due_until, title, description, priority, category, user_id FROM tasks WHERE user_id = ?
`

func (q *Queries) GetAllUsersTasks(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueUntil,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Category,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, created_at, updated_at, due_until, title, description, priority, category, user_id FROM tasks WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueUntil,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Category,
		&i.UserID,
	)
	return i, err
}

const getTaskByTitleAndDescription = `-- name: GetTaskByTitleAndDescription :many
SELECT id, created_at, updated_at, due_until, title, description, priority, category, user_id FROM tasks WHERE title LIKE ? OR description LIKE ?
`

type GetTaskByTitleAndDescriptionParams struct {
	Title       string
	Description string
}

func (q *Queries) GetTaskByTitleAndDescription(ctx context.Context, arg GetTaskByTitleAndDescriptionParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTaskByTitleAndDescription, arg.Title, arg.Description)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueUntil,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Category,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByDescription = `-- name: GetTasksByDescription :many
SELECT id, created_at, updated_at, due_until, title, description, priority, category, user_id FROM tasks WHERE description LIKE ?
`

func (q *Queries) GetTasksByDescription(ctx context.Context, description string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByDescription, description)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueUntil,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Category,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByTitle = `-- name: GetTasksByTitle :many
SELECT id, created_at, updated_at, due_until, title, description, priority, category, user_id FROM tasks WHERE title LIKE ?
`

func (q *Queries) GetTasksByTitle(ctx context.Context, title string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByTitle, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueUntil,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Category,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskByID = `-- name: UpdateTaskByID :one
UPDATE tasks
SET title = ?, description = ?, priority = ?, category = ?, updated_at = ?, due_until = ?
WHERE id = ?
RETURNING id, created_at, updated_at, due_until, title, description, priority, category, user_id
`

type UpdateTaskByIDParams struct {
	Title       string
	Description string
	Priority    int64
	Category    string
	UpdatedAt   time.Time
	DueUntil    time.Time
	ID          string
}

func (q *Queries) UpdateTaskByID(ctx context.Context, arg UpdateTaskByIDParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskByID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Category,
		arg.UpdatedAt,
		arg.DueUntil,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueUntil,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Category,
		&i.UserID,
	)
	return i, err
}
